SELECT * FROM DRAINAGEDITCH;
SELECT * FROM SLOPE;
SELECT * FROM CHAINAGE;

SELECT * FROM CHAINAGE C,SLOPE S
WHERE C.CHAINAGE = S .CHAINAGE;

SELECT * FROM SLOPE S
INNER JOIN CHAINAGE C
ON S.CHAINAGE = C.CHAINAGE;

SELECT * FROM CHAINAGE C
INNER JOIN SLOPE S
ON S.CHAINAGE = C.CHAINAGE;

DROP TABLE IF EXISTS typeofslopeprot
CREATE TABLE IF NOT EXISTS typeofslopeprot(
	`id` INT(2) NOT NULL AUTO_INCREMENT,
	`坡度min` FLOAT(10),
	`坡度max` FLOAT(10), 
	`坡高min` FLOAT(10),
	`坡高max` FLOAT(10), 
	`防护类型` VARCHAR(50),
	PRIMARY KEY (`id`)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

INSERT INTO typeofslopeprot VALUES(1,-10,-1,-4,0,'绿化')
INSERT INTO typeofslopeprot VALUES(2,-10,-1,-20,-4,'拱形骨架护坡');
SELECT * FROM typeofslopeprot

SELECT C.ID,S.*,T.防护类型
FROM CHAINAGE C, SLOPE S, TYPEOFSLOPEPROT T
WHERE C.CHAINAGE=S.CHAINAGE
AND S.左右侧=1
AND S.位于边沟左右侧=1
AND S.S坡度 BETWEEN T.坡度min AND T.坡度max
AND S.坡高 BETWEEN T.坡高min AND T.坡高max
ORDER BY c.id;

SELECT s.*,d.*
FROM slope s
LEFT JOIN drainageditch d
ON s.chainage=d.chainage AND s.左右侧=d.左右侧
ORDER BY s.id;

